---
title: "Analysing long-term work and family dynamics with R package xyz"
author: "Santtu, Jouni, Satu & Simon & Sanni?"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Potential venues:

Sociological Methodology if go application first style, perhaps with another software paper on Journal of Open Source Software or similar "light" journal. I can see a proper stats paper coming from this as well. No need to decide yet.

## Introduction

Studying individual-level life history data is important and difficult. Multiple approaches exists to analyze such data, for example, sequence analysis, hidden Markov models, etc. Here we introduce a general modelling framework and accompanying R package for flexible joint modelling of the interdependent dynamics of multivariate measurements from multiple individuals where these dependency structures can vary in time. And we apply it to some real data and find something interesting.

Consider an individual $i$ with observations $y_{i,t} = (y^1_{i,t}, \ldots, y^c_{i,t},\ldots, y^C_{i,t})$, $t=1,\ldots,T$, i.e. at each time point $t$ we have $C$ observations from individual $i$. Assume that each element of $y_{i,t}$ can depend on the past values $y_{i,t-1}$, as well as additional exogenous covariates $x_{i,t}$. Then, assuming that the elements of $y_{i,t}$ are independent given $y_{i, t-1}$ and $x_{i,t}$, we have
$$
\begin{aligned}
y_{i,t} &\sim p_t(y_{i,t} | y_{i,t-1},  x_{i,t}) = p^1_t(y^1_{i,t} | y^1_{i,t-1}, y^2_{i,t-1}, x_{i,t})p^2_t(y^2_{i,t} | y^1_{i,t-1}, y^2_{i,t-1}, x_{i,t}).
\end{aligned}
$$
Here the parameters of the conditional distributions $p^1$ and $p^2$ depend on time, which allows us to take into account the fact that the dynamics of our system can evolve over time. For example, something something life courses.

For $p^c_t$, given a suitable link function depending our distributional assumptions, we define a linear predictor $\eta^c_{t}$ for the channel $c$ with a following general form:

$$
\begin{aligned}
\eta^c_{t} &= X^c_{t} \beta^c_{t}\\
\beta^c_{k,t} &= B_t \delta_k^c, \quad k=1,\ldots,K,
\end{aligned}
$$
where $K$ is the number of covariates, $B_t$ is a vector of B-spline values at time $t$ and $\delta_k^c$ is vector of corresponding spline coefficients. In general the number of B-splines $D$ (number of knots) used for constructing the splines for the study period $1,\ldots,T$ can be chosen freely, and can often result in overfitting. To mitigate this, we define a random walk prior for $\delta^c_k$ as

$$
\begin{aligned}
\delta^c_{k,1} &\sim N(0, 1),\\
\delta^c_{k,d} &\sim N(\delta^c_{k,d-1}, (\tau^c_k)^2), \quad d=2,\ldots, D.\\
\end{aligned}
$$

Here $\tau^c_k$ controls the "wigglyness" of the spline curves. In some cases it can be though that the splines change values in approximately same time points. For this, we can construct a global shrinkage series $\lambda_2,\ldots, \lambda_D$ and define 
$$
\begin{aligned}
\delta^c_{k,d} &\sim N(\delta^c_{k,d-1}, (\tau^c_k\lambda_d)^2)\\
\tau^c_k &\sim Cauchy(0, 1)^+ \quad \textrm{(half-Cauchy distribution)}\\
\lambda_d &\sim N(0, 1)^+  \quad \textrm{(half-Normal distribution)}
\end{aligned}
$$
(not fully tested but might work) 
# Example

# Main functionality of the package

- How to build and estimate the model, supported distributions, how to define priors...
- How to interpret the results, visualization, posterior predictive checks, causal queries based on the posterior predictive distribution?

# Application

# Results

# Discussion


