# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# This is as CMD-check workflow of dynamite
# strike this -> but uses CRAN version of rstan and StanHeaders #
# does not use CRAN versions as they are broken:
# https://github.com/stan-dev/rstan/wiki/Configuring-C---Toolchain-for-Windows#r-42

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-CMD-check-cranrel

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release', rtools: '42'}
          - {os: ubuntu-latest,  r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      # this sets the env variable to true or false depending on whether the
      # commit message contains texts 'run-extended' and 'run-scaling'
      DYNAMITE_EXTENDED_TESTS: ${{contains(github.event.head_commit.message, 'run-extended')}}
      DYNAMITE_SCALING_TESTS: ${{contains(github.event.head_commit.message, 'run-scaling')}}

    steps:

      # alternative way to set up the environment variable
      # - name: Set the value of DYNAMITE_EXTENDED_TESTS
      #   if: contains(github.event.head_commit.message, 'run-extended')
      #   run: |
      #     if [ "$RUNNER_OS" == "Windows" ]; then
      #       echo "DYNAMITE_EXTENDED_TESTS=1" >> $env:GITHUB_ENV
      #     else
      #       echo "DYNAMITE_EXTENDED_TESTS=1" >> $GITHUB_ENV
      #     fi
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: |
            https://mc-stan.org/r-packages/
          r-version: ${{ matrix.config.r }}
          rtools-version: ${{ matrix.config.rtools }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            rcmdcheck
            BH
            RcppParallel
            RcppEigen
            Rcpp
            StanHeaders
            rstan
            cmdstanr

      - name: Build CmdStan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan()
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
